apiVersion: "harbor.turner.com/v1"
kind: ShipmentEnvironment
metadata:
  name: my-shipment-dev
  namespace: default
spec: 
  name: my-shipment
  environment: dev
  barge: ent-prod
  group: mss
  replicas: 3
  customer: turner
  team: cloudarch
  contact-email: cloudarch
  containers:
    - name: web
      image: gcr.io/google_containers/echoserver:1.4
      ports:
      - external: false
        healthcheck: /health
        name: http
        protocol: http
        public_port: 80
        value: 8080
  envvars:
    - name: FOO
      type: basic
      value: bar
status:
  state: ""
  message: ""
      